//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Room_Calc {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label label;
		
		protected System.Web.UI.HtmlControls.HtmlInputText id_length;
		
		protected System.Web.UI.HtmlControls.HtmlSelect id_material;
		
		protected System.Web.UI.HtmlControls.HtmlSelect id_color;
		
		protected System.Web.UI.HtmlControls.HtmlInputText id_employees;
		
		protected System.Web.UI.HtmlControls.HtmlInputText id_width;
		
		protected System.Web.UI.HtmlControls.HtmlInputText id_material_cost;
		
		protected System.Web.UI.HtmlControls.HtmlInputText id_color_cost;
		
		protected System.Web.UI.HtmlControls.HtmlInputText id_salary;
		
		protected System.Web.UI.WebControls.Button button1;
	}
}
